# Was noch nicht funkitoniert: Anlegen (mit success) und danach den State direkt wieder auslesen
# Vermutung: Wahrscheinlich muss die Statemachine released werden!!

###


POST http://localhost:8080/order/success
Content-Type: application/json

{
  "customer": "ABC Racing",
  "articleNumber": 2421,
  "count": 1
}

###

POST http://localhost:8080/order/fail
Content-Type: application/json

{
	"customer": "ABC Racing",
	"articleNumber": 2421,
	"count": 1
}

###

GET http://localhost:8080/retry/fail/14b89161-c261-4ac1-b787-1465d7232f8d


###

GET http://localhost:8080/retry/success/14b89161-c261-4ac1-b787-1465d7232f8d

###
GET http://localhost:8080/order/14b89161-c261-4ac1-b787-1465d7232f8d

###
# for ((i=1;i<=2000;i++)); do curl -s -X POST --location "http://localhost:8080/order/success" -H "Content-Type: application/json" -d "{\"customer\": \"ABC Racing\", \"articleNumber\": 2421, \"count\": 1}" > /dev/null; done
